routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//Auth::routes();

Route::group(['middleware' => ['guest:admin']], function () {
    Route::get('/login', 'AuthController@viewLogin')->name('login');
    Route::post('/login', 'AuthController@login');
});

Route::group(['middleware' => ['auth:admin', 'admin-active', 'auto-check-permission']], function () {

    Route::post('/logout', 'AuthController@logout')->name('logout');
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('attachment', 'AttachmentController');

    Route::get('reset-password', 'AuthController@ResetPasswordView');
    Route::post('reset-password', 'AuthController@ResetPassword');

    Route::resource('roles', 'RoleController');

    Route::get('users/toggle-boolean/{id}/{action}', 'UserController@toggleBoolean')->name('users.toggleBoolean');
    Route::resource('users', 'UserController');

    Route::get('settings', 'SettingsController@view')->name('settings-view');
    Route::post('settings', 'SettingsController@update')->name('settings-save');

    Route::resource('developer/setting', 'DeveloperSetting');
    Route::resource('developer/settings/categories', 'SettingCategoryController');

    //notifications
    Route::get('notifications/read/{id}', 'NotificationController@read');
    Route::resource('notifications', 'NotificationController');

    //logs
    Route::resource('logs', 'LogController');

    //emails
    Route::resource('emails', 'EmailController');

    //folders
    Route::resource('folders', 'FolderController');

    //files
    Route::resource('folder.files', 'FolderFileController');

    //files
    Route::get('file/{file}/contents/{content}/toggle-boolean/{action}', 'FileContentController@toggleBoolean')->name('contents.toggleBoolean');
    Route::resource('file.contents', 'FileContentController');
});

app/Models/User.php
<?php

namespace App\Models;

use App\Traits\GetAttribute;
use App\Traits\LogTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles, GetAttribute,LogTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guard_name = 'admin';
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function notifications()
    {
        return $this->morphToMany(Notification::class,'notifiable')->withPivot('is_read');
    }

    public function folders(){
        return $this->hasMany(Folder::class);
    }

    public function files(){
        return $this->hasMany(File::class);
    }

    public function emails()
    {
        return $this->hasMany(Email::class);
    }

    public function sharedFolders(){
        return $this->morphedByMany(Folder::class,'sharable','user_shares');
    }

    public function sharedFiles(){
        return $this->morphedByMany(File::class,'sharable','user_shares');
    }

    public function getNewNotifiCountAttribute()
    {
        return $this->notifications()->wherePivot('is_read', 0)->count();
    }

    public function getRolesListAttribute()
    {
        return $this->roles()->pluck('guard_name', 'id')->toArray();
    }

    public function getPhotoAttribute()
    {
        return $this->attachmentRelation()->count() ? asset($this->attachmentRelation()->first()->path) : asset('inspina/img/default.png');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace Admin;

use App\Http\Controllers\Controller;
use Helper\Helper;
use App\Traits\Master;
use Illuminate\Http\Request;
use \Illuminate\Support\Facades\DB;
use App\Http\Requests;
use App\Models\User;
use Response;
use Hash;
use Auth;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    use Master;

    public function __construct()
    {
        $this->model = new User();
        $this->viewsDomain = 'users.';
        $this->viewsUrl = 'users';
    }

    public function index(Request $request)
    {
        $users = User::where(function ($q) use ($request) {

            if($request->id){
                $q->where('id' , $request->id);
            }else{

                if ($request->name) {
                    $q->where(function ($q) use ($request) {

                        $q->where('name', 'LIKE', '%' . $request->name . '%')
                            ->orWhere('email', 'LIKE', '%' . $request->name . '%');
                    });
                }
                if ($request->role_name) {

                    $q->whereHas('roles', function ($q) use ($request) {

                        $q->where('display_name', 'LIKE', '%' . $request->role_name . '%');
                    });
                }

                if ($request->from) {
                    $q->whereDate('created_at', '>=', Helper::convertDateTime($request->from));
                }

                if ($request->to) {
                    $q->whereDate('created_at', '<=', Helper::convertDateTime($request->to));
                }

            }

        })->latest()->paginate(20);

        return $this->view('index', compact('users'));
    }

    public function create(User $model)
    {
        $model = new User();
        $roles = Role::all();

        return $this->view('create', compact('model', 'roles'));
    }

    public function store(Request $request)
    {
        $rules =
            [
                'name'     => 'required',
                'email'    => 'required|email|unique:users',
                'password' => 'required|confirmed',
                'roles.*'  => 'required|exists:roles,id',
            ];

        $error_sms =
            [
                'name.required'      => 'الرجاء ادخال الاسم ',
                'email.unique'       => ' البريد الالكتروني موجود بالفعل',
                'email.required'     => 'الرجاء ادخال البريد الالكتروني',
                'password.required'  => 'الرجاء ادخال كلمة المرور',
                'password.confirmed' => 'الرجاء التاكد من كلمة المرور ',

            ];

        $data = validator()->make($request->all(), $rules, $error_sms);

        if ($data->fails()) {
            return back()->withInput()->withErrors($data->errors());
        }

        DB::beginTransaction();
        $user = User::create(request()->all());

        $user->update(['password' => Hash::make($request->password)]);

        $user->assignRole($request->roles);
        DB::commit();
        session()->flash('success', 'تمت الاضافة بنجاح');
        return redirect('/users');
    }

    public function edit($id)
    {
        if ($id == 1)
            return redirect('users');

        $model = User::findOrFail($id);
        $roles = Role::all();

        return $this->view('edit', compact('model', 'roles'));
    }

    public function update(Request $request, $id)
    {
        if ($id == 1)
            return back();
        $record = User::findOrFail($id);

        $rules =
            [
                'name'     => 'required',
                'email'    => 'required|email|unique:users,email,' . $record->id . '',
                'password' => 'nullable|confirmed',
                'roles.*'  => 'required|exists:roles,id',
            ];

        $error_sms =
            [
                'name.required'      => 'الرجاء ادخال الاسم ',
                'email.required'     => 'الرجاء ادخال البريد الالكتروني',
                'email.unique'       => ' البريد الالكتروني موجود بالفعل',
                'password.required'  => 'الرجاء ادخال كلمة المرور ',
                'password.confirmed' => 'الرجاء التاكد من كلمة المرور ',
            ];

        $data = validator()->make($request->all(), $rules, $error_sms);

        if ($data->fails()) {
            return redirect('/users/' . $id . '/edit')->withInput()->withErrors($data->errors());
        }


        $record->update($request->except('password'));

        if ($request->has('password')) {
            $record->update(['password' => Hash::make($request->password)]);
        }

        DB::table('model_has_roles')->where('model_id', $id)->delete();
        $record->assignRole($request->roles);

        session()->flash('success', 'تم التعديل بنجاح');
        return back();

    }

    public function destroy($id)
    {
        $record = User::find($id);

        if (!$record) {
            return response()->json([
                'status' => 0,
                'message' => 'تعذر الحصول على البيانات'
            ]);
        }

        if (auth()->user()->id == $record->id) {
            session()->flash('fail', 'This email, you cannot deactivate it');
            return redirect('users');
        }

        DB::table('model_has_roles')->where('model_id', $id)->delete();
        $record->delete();
        $data = [
            'status' => 1,
            'msg'    => 'تم الحذ بنجاح',
            'id'     => $id
        ];

        return Response::json($data, 200);
    }


    public function toggleBoolean($id, $action)
    {
        $record = User::findOrFail($id);

        if (auth('admin')->user()->id == $record->id) {

            return Helper::responseJson(0, 'لا يمكنك إلغاء تفعيل حسابك ');
        }

        $activate = Helper::toggleBoolean($record, $action, 1, 0);

        if ($activate) {
            return Helper::responseJson(1, 'تمت العملية بنجاح');
        }

        return Helper::responseJson(0, 'حدث خطأ');
    }

    public function home()
    {
        return view('layouts.home');
    }
}

resources/views/users/create.blade.php
@extends('layouts.main',[
                                'page_header'       => 'المستخدمين',
                                'page_description'  => 'اضافة مستخدم',
								'link' => url('users')
                                ])


@section('content')
    <!-- general form elements -->
    <div class="ibox ibox-primary">
        <!-- form start -->
        {!! Form::model($model,[
                                'action'=>'Admin\UserController@store',
                                'id'=>'myForm',
                                'role'=>'form',
                                'method'=>'POST',
                                'files' => true
                                ])!!}

        <div class="ibox-content">

            @include('users.form')

            <div class="ibox-footer">
                <button type="submit" class="btn btn-primary">حفظ</button>
            </div>

        </div>
        {!! Form::close()!!}

    </div><!-- /.box -->

@endsection

resources/views/users/edit.blade.php
@extends('layouts.main',[
                                    'page_header'       => 'المستخدمين',
                                    'page_description'  => 'تعديل مستخدم',
								'link' => url('users')
                                ])
@section('content')
    <!-- general form elements -->
    <div class="ibox ibox-primary">
        <!-- form start -->
        {!! Form::model($model,[
                                'url'=>url('users/'.$model->id),
                                'id'=>'myForm',
                                'role'=>'form',
                                'method'=>'PUT',
                                'files' => true
                                ])!!}

        <div class="ibox-content">
            <div class="clearfix"></div>
            <br>
            @include('users.form')

            <div class="ibox-footer">
                <button type="submit" class="btn btn-primary">حفظ</button>
            </div>

        </div>
        {!! Form::close()!!}

    </div><!-- /.box -->

@endsection

resources/views/users/form.blade.php
{!! \Helper\Field::text('name' , 'الاسم')!!}
{!! \Helper\Field::email('email' , 'البريد الالكترونى') !!}
{!! \Helper\Field::password('password' , 'كلمة المرور') !!}
{!! \Helper\Field::password('password_confirmation' , 'تاكيد كلمة المرور') !!}
<br>
<div class="form-group" id="permissions_wrap">
    <label for="permissions">الرتب</label>
    <div class="">
        <br>

        @foreach( $roles as $role)

            <div class="form-group col-lg-4" id="roles_wrap">

                <div class="">
                    <input type="checkbox" name="roles[]" value="{{$role->id}}"
                            {{$model->hasRole($role->name) ? 'checked' : ''}}>

                    <label for="roles">{{$role->display_name}}</label>
                </div>
            </div>

        @endforeach
    </div>
    <br>
    <br>

</div>

resources/views/users/index.blade.php
@extends('layouts.main',[
								'page_header'		=> 'المستخدمين',
								'page_description'	=> 'عرض المستخدمين',

								'link' => url('users')
								])
@section('content')
    <div class="ibox ibox-primary">
        <div class="ibox-title">
            <div class="pull-right">
                <a href="{{url('users/create')}}" class="btn btn-primary">
                    <i class="fa fa-plus"></i>اضافة مستخدم جديد
                </a>
            </div>
            <div class="clearfix"></div>
        </div>

        <div class="">
            {!! Form::open([
                'method' => 'GET'
            ]) !!}
            <div class="col-md-3">
                <div class="">
                    <label for="">&nbsp;</label>
                    {!! Form::text('name',request('name'),[
                        'class' => 'form-control',
                        'placeholder' => 'الاسم'
                    ]) !!}
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="">&nbsp;</label>
                    {!! Form::text('role_name',request('role_name'),[
                        'class' => 'form-control',
                        'placeholder' => 'اسم الصلاحية'
                    ]) !!}
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label for="">&nbsp;</label>
                    {!! Form::text('from',request('from'),[
                        'class' => 'form-control datepicker',
                        'placeholder' => 'بداية تاريخ الاضافة'
                    ]) !!}
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label for="">&nbsp;</label>
                    {!! Form::text('to',request('to'),[
                        'class' => 'form-control datepicker',
                        'placeholder' => 'انتهاء تاريخ الاضافة'
                    ]) !!}
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label for="">&nbsp;</label>
                    <button class="btn btn-flat btn-block btn-primary">بحث</button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>

        <div class="ibox-content">
            @if(!empty($users) && count($users)>0)
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                        <th>#</th>
                        <th>الاسم</th>
                        <th>الايميل</th>
                        <th class="text-center">الصلاحيات</th>
                        <th class="text-center">الحالة</th>
                        <th class="text-center">تعديل</th>
                        <th class="text-center">حذف</th>
                        </thead>
                        <tbody>
                        @php $count = 1; @endphp
                        @foreach($users as $user)
                            <tr id="removable{{$user->id}}">
                                <td>{{$count}}</td>
                                <td>{{optional($user)->name}}</td>
                                <td>
                                    {{optional($user)->email}}
                                    <a class="btn btn-sm btn-info" href="{{url('emails/create?to='.$user->id)}}"><i class="fa fa-reply"></i> إرسال إيميل </a>
                                </td>
                                <td class="text-center">
                                    @if($user->roles()->count())
                                        @foreach($user->roles as $role)
                                            <div class="col-lg-4">
                                                <label style="    background-color: #19A689;
    color: white;
    width: 200px;
    text-align: center;
    padding: 6px 0px;
    border-radius: 6px;">{{$role->display_name}}</label>
                                            </div>
                                        @endforeach
                                    @else
                                        <label class="label label-danger">ليس لديه أي صلاحيات</label>
                                    @endif
                                </td>

                                @if($user->id === 1 || auth('admin')->user()->id == $user->id)
                                    <td class="text-center danger">لا يمكن ألغاء التفعيل</td>
                                @else
                                    <td class="text-center">

                                        {!! \Helper\Helper::toggleBooleanView($user ,
                                        url('users/toggle-boolean/'.$user->id.'/is_active/')) !!}

                                    </td>
                                @endif

                                @if($user->id === 1 || auth('admin')->user()->id == $user->id)
                                    <td class="text-center danger">لا يمكن التعديل</td>
                                @else

                                    <td class="text-center"><a href="{{url('users/' . $user->id .'/edit')}}"
                                                               class="btn btn-xs btn-success"><i class="fa fa-edit"></i></a>
                                    </td>

                                @endif

                                @if($user->id === 1 || auth('admin')->user()->id == $user->id)
                                    <td class="text-center danger">لا يمكن الحذف</td>
                                @else
                                    <td class="text-center">
                                        <button id="{{$user->id}}" data-token="{{ csrf_token() }}"
                                                data-route="{{URL::route('users.destroy',$user->id)}}" type="button"
                                                class="destroy btn btn-danger btn-xs"><i class="fa fa-trash-o"></i>
                                        </button>
                                    </td>
                                @endif
                            </tr>
                            @php $count ++; @endphp
                        @endforeach
                        </tbody>
                    </table>
                </div>
                {!! $users->render() !!}
            @else
                <div>
                    <h3 class="text-info" style="text-align: center">No data to show </h3>
                </div>
            @endif


        </div>
    </div>
@stop

@section('script')
    <script>
        lightbox.option({
            'resizeDuration': 200,
            'wrapAround': true,
            'showImageNumberLabel': false,

        })
    </script>
@stop