routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//Auth::routes();

Route::group(['middleware' => ['guest:admin']], function () {
    Route::get('/login', 'AuthController@viewLogin')->name('login');
    Route::post('/login', 'AuthController@login');
});

Route::group(['middleware' => ['auth:admin', 'admin-active', 'auto-check-permission']], function () {

    Route::post('/logout', 'AuthController@logout')->name('logout');
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('attachment', 'AttachmentController');

    Route::get('reset-password', 'AuthController@ResetPasswordView');
    Route::post('reset-password', 'AuthController@ResetPassword');

    Route::resource('roles', 'RoleController');

    Route::get('users/toggle-boolean/{id}/{action}', 'UserController@toggleBoolean')->name('users.toggleBoolean');
    Route::resource('users', 'UserController');

    Route::get('settings', 'SettingsController@view')->name('settings-view');
    Route::post('settings', 'SettingsController@update')->name('settings-save');

    Route::resource('developer/setting', 'DeveloperSetting');
    Route::resource('developer/settings/categories', 'SettingCategoryController');

    //notifications
    Route::get('notifications/read/{id}', 'NotificationController@read');
    Route::resource('notifications', 'NotificationController');

    //logs
    Route::resource('logs', 'LogController');

    //emails
    Route::resource('emails', 'EmailController');

    //folders
    Route::resource('folders', 'FolderController');

    //files
    Route::resource('folder.files', 'FolderFileController');

    //files
    Route::get('file/{file}/contents/{content}/toggle-boolean/{action}', 'FileContentController@toggleBoolean')->name('contents.toggleBoolean');
    Route::resource('file.contents', 'FileContentController');
});

app/Models/Folder.php
<?php

namespace App\Models;

use App\Traits\LogTrait;
use Illuminate\Database\Eloquent\Model;

class Folder extends Model 
{
    use LogTrait;

    static $status = [
        'private' => 'خاص',
        'public' => 'عام'
    ];
    protected $table = 'folders';
    public $timestamps = true;
    protected $fillable = array('name','status','user_id');

    public function files()
    {
        return $this->hasMany('App\Models\File');
    }

    public function creator()
    {
        return $this->belongsTo(User::class);
    }

    public function users()
    {
        return $this->morphToMany(User::class , 'sharable','user_shares');
    }

}

app/Http/Controllers/Admin/FolderController.php
<?php

namespace Admin;

use App\Models\Folder;
use App\Traits\Master;
use App\Traits\Query;
use Illuminate\Support\Facades\Artisan;
use Spatie\Permission\Models\Permission;
use \Spatie\Permission\Models\Role;
use Helper\Helper;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Response;

class FolderController extends Controller
{
    use Master,Query;

    public function __construct()
    {
        $this->model = new Folder();
        $this->viewsDomain = 'folders.';
        $this->viewsUrl = 'folders';
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->request = $request;

        $records = $this->folderPermission()->where(function ($q) use ($request) {

            if ($request->name) {
                $q->where(function ($q) use ($request) {

                    $q->where('name', 'LIKE', '%' . $request->name . '%');
                });
            }

            if ($request->from) {
                $q->whereDate('created_at', '>=', Helper::convertDateTime($request->from));
            }

            if ($request->to) {
                $q->whereDate('created_at', '<=', Helper::convertDateTime($request->to));
            }


        })->latest()->paginate(30)->appends(\Request::except('page'));

        return $this->view('index', compact('records'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = auth()->user();
        $rules =
            [
                'name' => 'required|unique:folders,name',
                'status' => 'required|in:public,private',
            ];

        $message =
            [
                'name.required' => 'الرجاء ادخال الاسم',
                'status.required' => 'الرجاء إختيار حالة المجلد',
                'name.unique' => 'يوجد المجلد بهذا الإسم بالفعل',

            ];

        $data = validator()->make($request->all(), $rules, $message);

        if ($data->fails())
            return $this->returnError($data);


        $record = $user->folders()->create($request->all());

        session()->flash('success', 'تمت الاضافة بنجاح');
        return $this->returnSuccess();
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        abort(404);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = auth()->user();
        $record = $user->folders()->findOrFail($id);


        $rules =
            [
                'edit_name' => 'required|unique:folders,name,'.$id,
                'edit_status' => 'required|in:public,private',
            ];

        $message =
            [
                'edit_name.required' => 'الرجاء ادخال الاسم',
                'edit_status.required' => 'الرجاء إختيار حالة المجلد',
                'edit_name.unique' => 'يوجد المجلد بهذا الإسم بالفعل',

            ];
        $data = validator()->make($request->all(), $rules, $message);

        if ($data->fails()) {
            session()->flash('fail', 'الرجاء ادخال الاسم');
            return back();
        }

        $request->merge([
            'name' => $request->edit_name,
            'status' => $request->edit_status,
        ]);
        $record->update($request->all());

        session()->flash('success', 'تمت التعديل بنجاح');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = auth()->user();
        $record = $user->folders()->findOrFail($id);

        if ($record->files()->count()) {
            $data = [
                'status' => 0,
                'msg' => ' فشل الحذف المجلد يحتوي علي بعض الملفات',
                'id' => $id
            ];
            return Response::json($data, 200);
        }

        $record->delete();

        $data = [
            'status' => 1,
            'msg' => 'تم الحذف بنجاح',
            'id' => $id
        ];
        return Response::json($data, 200);
    }
}

resources/views/folders/block-show.blade.php
<div class="attachment">
    @php $count = 1; @endphp
    @foreach($records as $record)

        <div class="file-box" id="removable{{$record->id}}">
            <div class="file">
                <div class="ibox-tools">

                    @if($record->user_id == auth()->user()->id)
                        @can('edit_folder')
                            <a onclick="openEditModel({{$record}})"><i
                                        class="fa fa-edit"></i></a>
                        @endcan

                        @can('delete_folder')
                            <button
                                    id="{{$record->id}}"
                                    data-token="{{ csrf_token() }}"
                                    data-route="{{URL::route('folders.destroy',$record->id)}}"
                                    type="button" class="destroy"
                                    style="color: #c7c7c7;background-color: #ffffff00;border: none;"
                            ><i class="fa fa-times"></i>
                            </button>
                        @endcan
                    @endif
                </div>
                <a href="{{url('folder/'.$record->id.'/files')}}">
                    <span class="corner"></span>

                    <div class="icon">
                        <i class="fa fa-folder-open" style="color: #ff980099;"></i>
                    </div>
                    <div class="file-name">
                        <span style="font-size: 1.6rem;">{{$record->name}}</span>
                        <span style="font-size: 1.6rem;float: left;">
                                            @if($record->status == 'private')
                                <i class="fa fa-lock"></i>
                            @else
                                <i class="fa fa-users"></i>
                            @endif
                                        </span>
                        <br>
                        <br>

                        <i class="fa fa-clock-o"></i>
                        <small>{{$record->created_at->locale('ar')->diffForHumans(Carbon\Carbon::now())}}</small>
                    </div>
                </a>
            </div>

        </div>

        @php $count ++; @endphp
    @endforeach
</div>

resources/views/folders/index.blade.php
@extends('layouts.main',[
								'page_header'		=> 'عرض المجلدات',
								'page_description'	=> 'عرض ',
								'link' => url('folders/'),
								'links' => [
								    'المجلدات' => url('folders/')
								],
								])
@section('content')


    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-3">
                <div class="ibox ">
                    <div class="ibox-content">
                        <div class="file-manager">

                            <a href="{{url('folders?show=block-show')}}" class="btn btn-info m-r-sm">
                                <i class="fa fa-th-large"></i>
                            </a>
                            <a href="{{url('folders?show=layer-show')}}" class="btn btn-info m-r-sm">
                                <i class="fa fa-th-list"></i>
                            </a>
                            <div class="hr-line-dashed"></div>
                            @can('add_folder')

                                <button class="btn btn-primary btn-block" data-toggle="modal" data-target="#add-new"><i
                                            class="fa fa-plus"></i> اضافة جديد
                                </button>
                                <div class="hr-line-dashed"></div>

                                <div class="modal fade" id="add-new" tabindex="-1" role="dialog"
                                     aria-labelledby="exampleModalLabel"
                                     aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">
                                                    إضافة جديد
                                                </h5>
                                                <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            {!! Form::open([
                                                                                                         'action'=>'Admin\FolderController@store',
                                                                                                         'id'=>'ajaxForm',
                                                                                                         'role'=>'form',
                                                                                                         'method'=>'POST',
                                                                                                         'files' => true
                                                                                                         ])!!}

                                            <div class=" modal-body">


                                                <div class="box-body">

                                                    {!! \Helper\Field::select('status' , 'الحالة', \App\Models\Folder::$status) !!}
                                                    {!! \Helper\Field::text('name' , 'إسم المجلد') !!}
                                                </div>
                                            </div>
                                            <div class="modal-footer">

                                                <div class="box-footer">
                                                    {!! \Helper\Field::ajaxBtn('حفظ') !!}
                                                    <button type="button" class="btn btn-secondary"
                                                            data-dismiss="modal">غلق
                                                    </button>
                                                </div>
                                            </div>

                                            {!! Form::close()!!}
                                        </div>
                                    </div>
                                </div>
                            @endcan

                            @can('edit_folder')
                                <div class="modal fade" id="edit-model" tabindex="-1" role="dialog"
                                     aria-labelledby="exampleModalLabel"
                                     aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">
                                                    تعديل
                                                </h5>
                                                <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            {!! Form::open([
                                                 'id'=>'editForm',
                                                 'role'=>'form',
                                                'method'=>'PUT',
                                                 'files' => true
                                                 ])!!}

                                            <div class=" modal-body">


                                                <div class="box-body">

                                                    {!! \Helper\Field::select('edit_status' , 'الحالة', \App\Models\Folder::$status) !!}
                                                    {!! \Helper\Field::text('edit_name' , 'إسم المجلد') !!}
                                                </div>
                                            </div>
                                            <div class="modal-footer">

                                                <div class="box-footer">
                                                    <button type="submit" class="btn btn-primary">حفظ</button>
                                                    <button type="button" class="btn btn-secondary"
                                                            data-dismiss="modal">غلق
                                                    </button>
                                                </div>
                                            </div>

                                            {!! Form::close()!!}
                                        </div>
                                    </div>
                                </div>
                            @endcan

                            <h3>البحث</h3>

                            {!! Form::open([
                                   'method' => 'get'
                                   ]) !!}
                            {!! Form::hidden('show' , request('show','block-show')) !!}
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        {!! Form::text('name',request()->input('name'),[
                                            'class' => 'form-control',
                                            'placeholder' => 'إسم المجلد'
                                        ]) !!}
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        {!! Form::select('folder_search_status',\App\Models\Folder::$status,request('folder_search_status'),[
                                                                        'class' => 'form-control',
                                                                        'placeholder' => 'كل المجلدات'
                                                                    ]) !!}
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        {!! Form::text('from',request()->input('from'),[
                                            'class' => 'form-control datepicker',
                                            'autocomplete' => 'off',
                                            'placeholder' => 'من'
                                        ]) !!}
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        {!! Form::text('to',\Request::input('to'),[
                                            'class' => 'form-control datepicker',
                                            'autocomplete' => 'off',
                                            'placeholder' => 'إلى'
                                        ]) !!}
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <button class="btn btn-flat btn-block btn-primary">بحث</button>
                                    </div>
                                </div>

                            </div>

                            {!! Form::close() !!}
                            <div class="hr-line-dashed"></div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 animated fadeInRight">
                <div class="row">
                    <div class="col-lg-12">

                        @if(!empty($records) && count($records)>0)
                            @include('folders.'.
                            (in_array(request('show' , 'block-show'),['block-show','layer-show'])
                                                    ? request('show' , 'block-show') : 'block-show'))


                            {!! $records->render() !!}
                        @else
                            <div>
                                <h3 class="text-info" style="text-align: center"> لا توجد بيانات للعرض </h3>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@can('edit_folder')
    <script>
        function openEditModel(model) {
            $('#editForm').attr('action', '{{url('folders')}}/' + model.id);

            $('#edit_name').val(model.name);
            $('#edit_status').val(model.status);
            $('#edit_status').select2().trigger('change');
            $('#edit-model').modal('show');
        }

    </script>
@endcan

resources/views/folders/layer-show.blade.php
<div class="col-lg-12">
    @php $count = 1; @endphp
    @foreach($records as $record)
        <div class="vote-item" style="padding-top: 3px;padding-left: 2px;">
            <div class="ibox-tools">

                @if($record->user_id == auth()->user()->id)
                    @can('edit_folder')
                        <a onclick="openEditModel({{$record}})"><i
                                    class="fa fa-edit"></i></a>
                    @endcan

                    @can('delete_folder')
                        <button
                                id="{{$record->id}}"
                                data-token="{{ csrf_token() }}"
                                data-route="{{URL::route('folders.destroy',$record->id)}}"
                                type="button" class="destroy"
                                style="color: #c7c7c7;background-color: #ffffff00;border: none;"
                        ><i class="fa fa-times"></i>
                        </button>
                    @endcan
                @endif
            </div>
            <div class="row">
                <div class="col-lg-10">
                    <a href="{{url('folder/'.$record->id.'/files')}}">
                        <div class="col-lg-2">
                            <div class="vote-icon">
                                <i class="fa fa-folder-open" style="color: #ff980099;"></i>
                            </div>
                        </div>
                        <p class="vote-title">
                            {{$record->name}}
                        </p>
                        <div class="vote-info">
                            @if($record->status == 'private')
                                <a href="#">خاص</a>
                                <i class="fa fa-lock"></i>
                            @else
                                <a href="#">عام</a>
                                <i class="fa fa-users"></i>
                            @endif
                            <a>
                                {{$record->created_at->locale('ar')->diffForHumans(Carbon\Carbon::now())}}
                            </a>
                            <i class="fa fa-clock-o"></i>

                        </div>
                    </a>
                </div>

            </div>
        </div>
        <br>
        @php $count ++; @endphp
    @endforeach
</div>