routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//Auth::routes();

Route::group(['middleware' => ['guest:admin']], function () {
    Route::get('/login', 'AuthController@viewLogin')->name('login');
    Route::post('/login', 'AuthController@login');
});

Route::group(['middleware' => ['auth:admin', 'admin-active', 'auto-check-permission']], function () {

    Route::post('/logout', 'AuthController@logout')->name('logout');
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('attachment', 'AttachmentController');

    Route::get('reset-password', 'AuthController@ResetPasswordView');
    Route::post('reset-password', 'AuthController@ResetPassword');

    Route::resource('roles', 'RoleController');

    Route::get('users/toggle-boolean/{id}/{action}', 'UserController@toggleBoolean')->name('users.toggleBoolean');
    Route::resource('users', 'UserController');

    Route::get('settings', 'SettingsController@view')->name('settings-view');
    Route::post('settings', 'SettingsController@update')->name('settings-save');

    Route::resource('developer/setting', 'DeveloperSetting');
    Route::resource('developer/settings/categories', 'SettingCategoryController');

    //notifications
    Route::get('notifications/read/{id}', 'NotificationController@read');
    Route::resource('notifications', 'NotificationController');

    //logs
    Route::resource('logs', 'LogController');

    //emails
    Route::resource('emails', 'EmailController');

    //folders
    Route::resource('folders', 'FolderController');

    //files
    Route::resource('folder.files', 'FolderFileController');

    //files
    Route::get('file/{file}/contents/{content}/toggle-boolean/{action}', 'FileContentController@toggleBoolean')->name('contents.toggleBoolean');
    Route::resource('file.contents', 'FileContentController');
});

app/Models/Content.php
<?php

namespace App\Models;

use App\Traits\GetAttribute;
use App\Traits\LogTrait;
use Illuminate\Database\Eloquent\Model;

class Content extends Model 
{
    use LogTrait;
    use GetAttribute;

    protected $table = 'contents';
    public $timestamps = true;
    protected $fillable = array('file_id', 'title','description');


    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->multiple_attachment = true;
    }

    public function notifications()
    {
        return $this->morphMany(Notification::class , 'notifiable');
    }

    public function file()
    {
        return $this->belongsTo('App\Models\File');
    }

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function getCreatorAttribute()
    {
        return $this->logs()->where('action' , 'add')->first() ? User::find($this->logs()->where('action' , 'add')->first()->user_id) : null;
    }

}

app/Models/User.php
<?php

namespace App\Models;

use App\Traits\GetAttribute;
use App\Traits\LogTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles, GetAttribute,LogTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guard_name = 'admin';
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function notifications()
    {
        return $this->morphToMany(Notification::class,'notifiable')->withPivot('is_read');
    }

    public function folders(){
        return $this->hasMany(Folder::class);
    }

    public function files(){
        return $this->hasMany(File::class);
    }

    public function emails()
    {
        return $this->hasMany(Email::class);
    }

    public function sharedFolders(){
        return $this->morphedByMany(Folder::class,'sharable','user_shares');
    }

    public function sharedFiles(){
        return $this->morphedByMany(File::class,'sharable','user_shares');
    }

    public function getNewNotifiCountAttribute()
    {
        return $this->notifications()->wherePivot('is_read', 0)->count();
    }

    public function getRolesListAttribute()
    {
        return $this->roles()->pluck('guard_name', 'id')->toArray();
    }

    public function getPhotoAttribute()
    {
        return $this->attachmentRelation()->count() ? asset($this->attachmentRelation()->first()->path) : asset('inspina/img/default.png');
    }
}

resources/views/contents/create.blade.php
@extends('layouts.main',[
                                'page_header'       => 'المقالات',
                                'page_description'  => 'إضافة ',
								'link' => url('file/'.$file->id.'/contents')
                                ])

@section('content')
    <!-- general form elements -->
    <div class="ibox ibox-primary">
        <!-- form start -->
        {!! Form::model($record,[
                                'action'=>['Admin\FileContentController@store', $file->id],
                                'id'=>'ajaxForm',
                                'role'=>'form',
                                'method'=>'POST',
                                'files' => true
                                ])!!}

        <div class="ibox-content">

            @include('contents.form')

            <div class="ibox-footer">
                {!! \Helper\Field::ajaxBtn('حفظ') !!}
            </div>

        </div>
        {!! Form::close()!!}

    </div><!-- /.box -->

@endsection

resources/views/contents/edit.blade.php
@extends('layouts.main',[
                                'page_header'       => 'المقالات',
                                'page_description'  => 'تعديل ',
								'link' => url('file/'.$file->id.'/contents')
                                ])
@section('content')
    <!-- general form elements -->
    <div class="ibox ibox-primary">
        <!-- form start -->
        {!! Form::model($record,[
                                'url'=>url('file/'.$file->id.'/contents/'.$record->id),
                                'id'=>'ajaxForm',
                                'role'=>'form',
                                'method'=>'PUT',
                                'files' => true
                                ])!!}

        <div class="ibox-content">
            <div class="clearfix"></div>
            <br>
            @include('contents.form')

            <div class="ibox-footer">
                {!! \Helper\Field::ajaxBtn('حفظ') !!}
            </div>

        </div>
        {!! Form::close()!!}

    </div><!-- /.box -->

@endsection

resources/views/contents/form.blade.php
@inject('users','App\Models\User')

{!! \Helper\Field::checkBox('users','المستخدمين',$users->pluck('name','id')->toArray() ,
$record->users()->count() ? $record->users->pluck('id')->toArray():null) !!}

{!! \Helper\Field::text('title' , 'العنوان ')!!}
{!! \Helper\Field::editor('description' , 'المحتوي بالإنجليزية')!!}
{!! \Helper\Field::radio('is_access' , 'قابل للتعديل' , [1=>'نعم',0=>'لا'], $record->is_access)!!}


{!! \Helper\Field::multiFileUpload('attachments','المرفقات') !!}



@if($record->attachmentRelation()->count())
    <div class="mail-attachment">
        <p>
            <span><i class="fa fa-paperclip"></i>
                المرفقات  </span>
        </p>

        <div class="attachment">

            @foreach($record->attachmentRelation()->get() as $attachment)
                <div class="file-box" id="removable{{$attachment->id}}">
                    <div class="file">
                        <div class="ibox-tools">
                            <button
                                    id="{{$attachment->id}}"
                                    data-token="{{ csrf_token() }}"
                                    data-route="{{URL::route('attachment.destroy',$attachment->id)}}"
                                    type="button" class="destroy"
                                    style="color: #c7c7c7;background-color: #ffffff00;border: none;"
                            ><i class="fa fa-times"></i>
                            </button>

                        </div>
                        <a href="#">
                            <span class="corner"></span>

                            @if($attachment->type == 'file')
                                <div class="icon">
                                    <i class="fa fa-file"></i>
                                </div>
                            @else
                                <div class="image">
                                    <img alt="image" class="img-fluid img-responsive"
                                         src="{{url($attachment->path)}}">
                                </div>
                            @endif
                            <div class="file-name">
                                {{$attachment->name}}
                                <br>
                                <small>
                                    أضيف :
                                    {{$record->created_at->locale('ar')->isoFormat('dddd  , MMMM  ,  Do / YYYY  ,  الساعة h:mm a')}}
                                </small>
                            </div>
                        </a>
                    </div>

                </div>
            @endforeach
            <div class="clearfix"></div>
        </div>
    </div>
@endif

resources/views/contents/index.blade.php
@extends('layouts.main',[
								'page_header'		=> 'عرض المقالات',
								'page_description'	=> 'عرض ',
								'link' => url('file/'.$file->id.'/contents')
								])
@section('content')

    <div class="ibox box-primary">

        @can('add_content')
            <div class="ibox-title">
                <div class="pull-right">
                    <a class="btn btn-primary" href="{{url('file/'.$file->id.'/contents/create')}}">
                        <i class="fa fa-plus"></i> اضافة جديد
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
        @endcan

        <div class="ibox-content">

            <div class="box-header">
                {!! Form::open([
                       'method' => 'get'
                       ]) !!}
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            {!! Form::text('id',request()->input('id'),[
                                'class' => 'form-control',
                                'placeholder' => 'رقم الملف'
                            ]) !!}
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            {!! Form::text('name',request()->input('name'),[
                                'class' => 'form-control',
                                'placeholder' => 'إسم الملف'
                            ]) !!}
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="form-group">
                            {!! Form::text('from',request()->input('from'),[
                                'class' => 'form-control datepicker',
                                'autocomplete' => 'off',
                                'placeholder' => 'من'
                            ]) !!}
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="form-group">
                            {!! Form::text('to',\Request::input('to'),[
                                'class' => 'form-control datepicker',
                                'autocomplete' => 'off',
                                'placeholder' => 'إلى'
                            ]) !!}
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="form-group">
                            <button class="btn btn-flat btn-block btn-primary">بحث</button>
                        </div>
                    </div>

                    {!! Form::close() !!}
                </div>
            </div>

        </div>
        <br><br>
        @if(!empty($records) && count($records)>0)
            @php $count = 1; @endphp
            <div class="row">
                @foreach($records as $record)
                    <div class="col-lg-6 animated fadeInRight" id="removable{{$record->id}}">

                        <div class="mail-box-header" style="padding: 5px 0px 15px 4px;">
                            <label class="label label-lg label-inverse"
                                   style="float:right;font-size: 1.5rem;">#{{$record->id}}</label>
                            <div class="tooltip-demo" style="text-align: left;margin-bottom: -5px;">

                                @can('logs_index')

                                    <a href="{{url('logs?type=content&id='.$record->id)}}"
                                       class="btn btn-warning btn-sm"
                                       data-toggle="tooltip" data-placement="top" title=""
                                       data-original-title="Print email">
                                        <i class="fa fa-eye"></i> سجل العميلات
                                    </a>
                                @endcan

                                @can('edit_content')

                                    <a href="{{url('file/' . $file->id .'/contents/'.$record->id.'/edit')}}"
                                       class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="top"
                                       title=""
                                       data-original-title="Print email">
                                        <i class="fa fa-pencil"></i> تعديل
                                    </a>
                                @endcan

                                @can('delete_content')

                                    <button
                                            id="{{$record->id}}"
                                            data-token="{{ csrf_token() }}"
                                            data-route="{{URL::route('file.contents.destroy',[$file->id , $record->id])}}"
                                            type="button"
                                            class="destroy btn btn-danger btn-sm">
                                        <i class="fa fa-trash-o"></i> حذف
                                    </button>
                                @endcan

                            </div>
                        </div>
                        <div class="mail-box-header">

                            <h2>
                                {{$record->title}}
                            </h2>
                            <div class="mail-tools tooltip-demo m-t-md">
                                <br>
                                <div class="user-friends">
                                    @if($record->creator)
                                        <span class="float-right font-normal">
                                            <strong>تمت الإضافه بواسطه :</strong>
                                            <a href="{{url('users?id='.$record->creator->id)}}">{{$record->creator->name}}</a>
                                        </span>
                                    @endif
                                    @if($record->users()->count())
                                        <br>
                                        <br>
                                        <p><strong>المرفقين :</strong></p>
                                        @foreach($record->users()->get() as $user)
                                            <a href="{{url('users?id='.$user->id)}}" title="test">
                                                <img alt="image" class="rounded-circle img-circle"
                                                     title="{{$user->name}}" src="{{$user->photo}}">
                                            </a>
                                        @endforeach
                                    @endif
                                </div>
                                <h5>
                                    <br>
                                    <span class="float-left font-normal" style="float: left">
                                    {{$record->created_at->locale('ar')->isoFormat('dddd  , MMMM  ,  Do / YYYY  ,  الساعة h:mm a')}}
                                </span>
                                </h5>
                            </div>
                        </div>
                        <div class="mail-box">


                            <div class="mail-body">
                                <p>
                                    <strong>التفاصيل</strong>
                                    <br>
                                    <br>
                                    {!! $record->description !!}
                                </p>
                            </div>

                            @if($record->attachmentRelation()->count())
                                <div class="mail-attachment">
                                    <p>

                        <span><i class="fa fa-paperclip"></i>
                            <span class="badge badge-primary"> {{$record->attachmentRelation()->count()}} </span>
                            المرفقات - </span>
                                        <a href="#">تحميل الكل</a>
                                    </p>

                                    <div class="attachment">

                                        @foreach($record->attachmentRelation()->get() as $attachment)
                                            <div class="file-box">
                                                <div class="file">
                                                    <a href="#">
                                                        <span class="corner"></span>

                                                        @if($attachment->type == 'file')
                                                            <div class="icon">
                                                                <i class="fa fa-file"></i>
                                                            </div>
                                                        @else
                                                            <div class="image">
                                                                <img alt="image" class="img-fluid img-responsive"
                                                                     src="{{url($attachment->path)}}">
                                                            </div>
                                                        @endif
                                                        <div class="file-name">
                                                            {{$attachment->name}}
                                                            <br>
                                                            <small>
                                                                أضيف :
                                                                {{$record->created_at->locale('ar')->isoFormat('dddd  , MMMM  ,  Do / YYYY  ,  الساعة h:mm a')}}
                                                            </small>
                                                        </div>
                                                    </a>
                                                </div>

                                            </div>
                                        @endforeach
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                            @endif

                            @can('access_switch_content')
                                <div class="mail-body text-right tooltip-demo">
                                    <label class="label label-primary" style="font-size: 1.2rem;margin-left: 8px;">
                                        <i class="fa fa-newspaper-o"></i> حالة المقال
                                    </label>
                                    {!! \Helper\Helper::toggleBooleanView($record , url('file/'.$file->id.'/contents/'.$record->id.'/toggle-boolean/is_access'),'is_access') !!}

                                    <br><br>
                                    <p>(للقرأه فقط أو القرائه و التعديل)</p>
                                </div>
                            @endcan
                            <div class="clearfix"></div>
                        </div>
                    </div>

                    @php $count ++; @endphp
                    @if($count % 2)
                        <div class="clearfix"></div>
                    @endif
                @endforeach
            </div>

            {!! $records->render() !!}
        @else
            <div class="alert alert-danger text-center">لا يوجد بيانات</div>
        @endif
    </div>
@stop