routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//Auth::routes();

Route::group(['middleware' => ['guest:admin']], function () {
    Route::get('/login', 'AuthController@viewLogin')->name('login');
    Route::post('/login', 'AuthController@login');
});

Route::group(['middleware' => ['auth:admin', 'admin-active', 'auto-check-permission']], function () {

    Route::post('/logout', 'AuthController@logout')->name('logout');
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('attachment', 'AttachmentController');

    Route::get('reset-password', 'AuthController@ResetPasswordView');
    Route::post('reset-password', 'AuthController@ResetPassword');

    Route::resource('roles', 'RoleController');

    Route::get('users/toggle-boolean/{id}/{action}', 'UserController@toggleBoolean')->name('users.toggleBoolean');
    Route::resource('users', 'UserController');

    Route::get('settings', 'SettingsController@view')->name('settings-view');
    Route::post('settings', 'SettingsController@update')->name('settings-save');

    Route::resource('developer/setting', 'DeveloperSetting');
    Route::resource('developer/settings/categories', 'SettingCategoryController');

    //notifications
    Route::get('notifications/read/{id}', 'NotificationController@read');
    Route::resource('notifications', 'NotificationController');

    //logs
    Route::resource('logs', 'LogController');

    //emails
    Route::resource('emails', 'EmailController');

    //folders
    Route::resource('folders', 'FolderController');

    //files
    Route::resource('folder.files', 'FolderFileController');

    //files
    Route::get('file/{file}/contents/{content}/toggle-boolean/{action}', 'FileContentController@toggleBoolean')->name('contents.toggleBoolean');
    Route::resource('file.contents', 'FileContentController');
});

app/Http/Controllers/Admin/RoleController.php
<?php

namespace Admin;

use App\Traits\Master;
use Illuminate\Support\Facades\Artisan;
use Spatie\Permission\Models\Permission;
use \Spatie\Permission\Models\Role;
use Helper\Helper;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Response;

class RoleController extends Controller
{
    use Master;

    public function __construct()
    {
        $this->model = new Role();
        $this->viewsDomain = 'roles.';
        $this->viewsUrl = 'roles';
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $roles = Role::where(function($q) use($request){
            if($request->name)
            {
                $q->where(function ($q) use($request){

                    $q->where('display_name','LIKE','%'.$request->name.'%');
                });
            }

            if ($request->from)
            {
                $q->whereDate('created_at' , '>=' , Helper::convertDateTime($request->from));
            }

            if ($request->to)
            {
                $q->whereDate('created_at' , '<=' , Helper::convertDateTime($request->to));
            }


        })->latest()->paginate(20);

        return $this->view('index' , compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        Artisan::call('permission:cache-reset');
        $model = new Role();
        $permissions = Permission::orderBy('order')->get();
        return $this->view('create',compact('model' , 'permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules=
            [
                'name'=>'required|unique:roles',
                'display_name'=>'required',

            ];

        $message=
            [
                'name.required'=>'الرجاء ادخال الاسم',
                'name.unique'=>'تم اخال هذه الصلاحية من قبل',
                'display_name.required'=>'الرجاء اخال الاسم المعروض',

            ];

        $data = validator()->make($request->all(),$rules , $message);
        if($data->fails())
        {
            return back()->withInput()->withErrors($data->errors());
        }

        $record = Role::create(request()->all());

        if($request->permissions)
            $record->permissions()->attach($request->permissions);

        session()->flash('success', 'تمت الاضافة بنجاح');
        return redirect('roles');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if($id == 2)
            return redirect('roles');

        Artisan::call('permission:cache-reset');
        $model = Role::findOrFail($id);

        $permissions = Permission::orderBy('order')->get();

        return $this->view('edit', compact('model' , 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $record = Role::findOrFail($id);

        $rules=
            [
                'name'=>'required|unique:roles,name,'.$record->id.'',
                'display_name'=>'required',
                'permissions'=>'required',

            ];

        $message=
            [
                'name.required'=>'الرجاء ادخال الاسم',
                'name.unique'=>'تم اخال هذه الصلاحية من قبل',
                'display_name.required'=>'الرجاء اخال الاسم المعروض',

            ];
        $data = validator()->make($request->all(),$rules,$message);

        if($data->fails())
        {
            return back()->withInput()->withErrors($data->errors());
        }

        $record ->update($request->all());
        $record->permissions()->sync($request->permissions);

        session()->flash('success', 'تمت التعديل بنجاح');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {


        $record = Role::findOrFail($id);

        $users = $record->users()->get();

        if(!count($users) || $id != 2)
        {
            $record->permissions()->detach();
            $record->delete();

            $data = [
                'status' => 1,
                'msg' => 'تم الحذف بنجاح',
                'id' => $id
            ];
            return Response::json($data, 200);
        }else
        {
            $data = [
                'status' => 0,
                'msg' => ' فشل الحذف , يوجد مستخدمين مرتبطين بهذه الصلاحية',
                'id' => $id
            ];
            return Response::json($data, 200);
        }
    }
}

resources/views/roles/create.blade.php
@extends('layouts.main',[
                                'page_header'       => 'الصلاحيات',
                                'page_description'  => '  صلاحية جديد ',
                                'link' => url('roles')
                                ])
@section('content')
        <!-- general form elements -->
<div class="box box-primary">
    <!-- form start -->
    {!! Form::model($model,[
                            'action'=>'Admin\RoleController@store',
                            'id'=>'myForm',
                            'role'=>'form',
                            'method'=>'POST',
                            'files' => true
                            ])!!}

    <div class="box-body">

        @include('roles.form')

        <div class="box-footer">
            <button type="submit" class="btn btn-primary">حفظ</button>
        </div>

    </div>
    {!! Form::close()!!}

</div><!-- /.box -->

@endsection

resources/views/roles/edit.blade.php
@extends('layouts.main',[
                                'page_header'       => 'الصلاحيات',
                                'page_description'  => ' تعديل  ',
                                'link' => url('roles')
                                ])
@section('content')
        <!-- general form elements -->
<div class="box box-primary">
    <!-- form start -->
    {!! Form::model($model,[
                            'url'=>url('roles/'.$model->id),
                            'id'=>'myForm',
                            'role'=>'form',
                            'method'=>'PUT',
                            'files' => true
                            ])!!}

    <div class="box-body">
        <div class="clearfix"></div>
        <br>
        @include('roles.form')

        <div class="box-footer">
            <button type="submit" class="btn btn-primary">حفظ</button>
        </div>

    </div>
    {!! Form::close()!!}

</div><!-- /.box -->

@endsection

resources/views/roles/form.blade.php
{!! \Helper\Field::text('name' , 'الاسم الصلاحية' )!!}
{!! \Helper\Field::text('display_name' , 'الاسم المعروض' ) !!}
<br>
<div class="form-group" id="permissions_wrap">
    <label for="permissions">الصلاحيات</label>
    <div class="">
        <br>

        <div class="form-group col-lg-12">

            <div class="">
                <span style="    color: white;
    background-color: #3c8cbc;
    padding: 9px 9px;
    border-radius: 6px;">
                    <input type="checkbox" onClick="toggle(this , 'permissions')" name="sellectAll">

                    <label for="sellectAll">تحديد الكل</label>
                </span>
            </div>
        </div>

        <div class="clearfix"></div>

        @php
            $title = '';
        @endphp
        @foreach( $permissions as $permission)
            @if ($loop->first)
                @php
                    $title = $permission->category;
                @endphp

                <div class="clearfix"></div>
                <br>
                <br>
                <div class="text-center">
                    <label style="    font-size: 1.6rem;
    color: #3c8cbc;">{{$permission->category}}</label>
                    <hr style="    width: 149px;
    padding: 1px 2px;
    background-color: #3c8cbc;">
                </div>
            @endif
            @if($permission->category != $title)
                <div class="clearfix"></div>
                <br>
                <br>
                <div class="text-center">
                    <label style="    font-size: 1.6rem;
    color: #3c8cbc;">{{$permission->category}}</label>
                    <hr style="    width: 149px;
    padding: 1px 2px;
    background-color: #3c8cbc;">
                </div>
            @endif

            <div class="form-group col-lg-4" id="permissions_wrap">

                <div class="">
                    <input type="checkbox" name="permissions[]" value="{{$permission->id}}"
                            {{$model->hasPermissionTo($permission->name) ? 'checked' : ''}}>

                    <label for="permissions">{{$permission->display_name}}</label>
                </div>
            </div>

            @php
                $title = $permission->category;
            @endphp

        @endforeach
    </div>

    <div class="clearfix"></div>

</div>
<br>
<br>

resources/views/roles/index.blade.php
@extends('layouts.main',[
								'page_header'		=> 'الصلاحيات',
								'page_description'	=> 'عرض الصلاحيات',
								'link' => url('roles')
								])
@section('content')
    <div class="ibox box-primary">
        <div class="ibox-title">
            <div class="pull-right">
                <a href="{{url('roles/create')}}" class="btn btn-primary">
                    <i class="fa fa-plus"></i> اضافة صلاحية جديد
                </a>
            </div>
            <div class="clearfix"></div>
        </div>

        <div class="row">
            {!! Form::open([
                'method' => 'GET'
            ]) !!}
            <div class="col-md-3">
                <div class="form-group">
                    <label for="">&nbsp;</label>
                    {!! Form::text('name',old('name'),[
                        'class' => 'form-control',
                        'placeholder' => 'الاسم'
                    ]) !!}
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label for="">&nbsp;</label>
                    {!! Form::text('from',old('from'),[
                        'class' => 'form-control datepicker',
                        'placeholder' => 'بداية تاريخ الاضافة'
                    ]) !!}
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label for="">&nbsp;</label>
                    {!! Form::text('to',old('to'),[
                        'class' => 'form-control datepicker',
                        'placeholder' => 'انتهاء تاريخ الاضافة'
                    ]) !!}
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label for="">&nbsp;</label>
                    <button class="btn btn-flat btn-block btn-primary">بحث</button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>

        <div class="ibox-content">
            @if(!empty($roles) && count($roles)>0)
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                        <th>#</th>
                        <th>الاسم </th>
                        <th class="text-center">التفاصيل</th>
                        <th class="text-center">تعديل</th>
                        <th class="text-center">حذف</th>
                        </thead>
                        <tbody>
                        @php $count = 1; @endphp
                        @foreach($roles as $role)
                            <tr id="removable{{$role->id}}">
                                <td>{{$count}}</td>
                                <td>{{optional($role)->display_name}}</td>
                                <td>
                                    <center>
                                        <button style="background-color: white;border: none" data-toggle="modal"
                                                data-target="#client{{$role->id}}"
                                        >
                                            <i class="btn btn-xs btn-info fa fa-eye" style="padding: 4px 6px"></i>
                                        </button>
                                    </center>

                                    <!-- Modal -->
                                    <div class="modal fade" id="client{{$role->id}}" tabindex="-1" role="dialog"
                                         aria-labelledby="myModalLabel">

                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal"
                                                            aria-label="Close"><span aria-hidden="true">&times;</span>
                                                    </button>


                                                    <h2 style="font-weight: bold" class="modal-title"
                                                        id="myModalLabel">{{$role->display_name}}</h2>
                                                </div>

                                                <div class="modal-body">
                                                    <p><strong>التفاصيل  : </strong> {!! $role->description !!}</p>
                                                    <p><strong>التحكم  : </strong> </p>
                                                    @php
                                                        $title = '';
                                                    @endphp
                                                    @foreach($role->permissions as $perm)
                                                        @if ($loop->first)
                                                            @php
                                                                $title = $perm->category;
                                                            @endphp

                                                            <div class="clearfix"></div>
                                                            <br>
                                                            <br>
                                                            <div class="text-center">
                                                                <label style="    font-size: 1.6rem;
    color: #3c8cbc;">{{$perm->category}}</label>
                                                                <hr style="    width: 149px;
    padding: 1px 2px;
    background-color: #3c8cbc;">
                                                            </div>
                                                        @endif
                                                        @if($perm->category != $title)
                                                            <div class="clearfix"></div>
                                                            <br>
                                                            <br>
                                                            <div class="text-center">
                                                                <label style="    font-size: 1.6rem;
color: #3c8cbc;">{{$perm->category}}</label>
                                                                <hr style="    width: 149px;
padding: 1px 2px;
background-color: #3c8cbc;">
                                                            </div>
                                                        @endif
                                                        <div class="col-sm-4">
                                                            <label style="   background-color: #04b904;
    color: white;
    border-radius: 6px;
    width: 100%;
    text-align: center;
    padding: 18px 0px;">{{$perm->display_name}}</label>
                                                        </div>
                                                            @php
                                                                $title = $perm->category;
                                                            @endphp

                                                    @endforeach
                                                    <br>
                                                    <br>
                                                </div>
                                                <div class="clearfix"></div>
                                                <br>
                                                <div class="modal-footer">
                                                    <p><strong>تاريخ الاضافة
                                                            : </strong> {{$role->created_at->locale('ar')->isoFormat('dddd  , MMMM  ,  Do / YYYY  ,  الساعة h:mm')}}
                                                    </p>
                                                    <button type="button" class="btn btn-default" data-dismiss="modal"
                                                            style="background-color: #00c0ef;color: white">
                                                        إغلاق
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>


                                @if($role->id === 2)
                                    <td class="text-center danger" colspan="2">لا يمكن الحذف أو التعديل</td>
                                @else
                                    <td class="text-center">
                                        <a href="{{url('roles/' . $role->id .'/edit')}}" class="btn btn-xs btn-success"><i class="fa fa-edit"></i></a></td>

                                    <td class="text-center">
                                        <button id="{{$role->id}}" data-token="{{ csrf_token() }}" data-route="{{URL::route('roles.destroy',$role->id)}}"  type="button" class="destroy btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></button>
                                    </td>

                                @endif


                            </tr>
                            @php $count ++; @endphp
                        @endforeach
                        </tbody>
                    </table>
                </div>
                {!! $roles->render() !!}
            @else
                <div>
                    <h3 class="text-info" style="text-align: center"> لا توجد بيانات للعرض </h3>
                </div>
            @endif


        </div>
    </div>
@stop

@section('script')
    <script>
        lightbox.option({
            'resizeDuration': 200,
            'wrapAround': true,
            'showImageNumberLabel':false,

        })
    </script>
@stop